---
title: "R Notebook"
output: html_notebook
---

## Week 6: Data Visualization


```{r}

library(tidyverse)

mpg

# Creating a graph

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))


```


```{r}

# Differentiating by color
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = class))


# Differentiating by size
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, size = class))

# Differentiating by transparency
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, alpha = class))

# Differentiating by shape
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, shape = class))

```

```{r}

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), shape = 12)

```

```{r}

# Faceting
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_wrap(~ class, nrow = 2)


ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_grid(drv ~ cyl)

```


```{r}

# Plotting a point
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))

#Plotting a line
ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy))

```



```{r}

# Plotting a point
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))

#Plotting a line
ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy))

# Adding multiple geom functions
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = drv)) +
  geom_smooth(mapping = aes(x = displ, y = hwy))

```


## Statistical transformations

```{r}

demo <- tribble(
  ~cut,         ~freq,
  "Fair",       1610,
  "Good",       4906,
  "Very Good",  12082,
  "Premium",    13791,
  "Ideal",      21551
)


# Plot by count
ggplot(data = demo) +
  geom_bar(mapping = aes(x = cut, y = freq), stat = "identity")

# Plot by proportion
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, y = ..prop.., group = 1))

# Plot by summary
ggplot(data = diamonds) + 
  stat_summary(
    mapping = aes(x = cut, y = depth),
    fun.ymin = min,
    fun.ymax = max,
    fun.y = median
  )

```

## Position adjustments

```{r}

# Stacked by clarity
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity))

# Transparency
ggplot(data = diamonds, mapping = aes(x = cut, fill = clarity)) + 
  geom_bar(alpha = 1/5, position = "identity")

#Stacked proportion bars
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "fill")

# Overlapping objects
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "dodge")

```

## Coordinate systems

```{r}

ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + 
  geom_boxplot()

ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + 
  geom_boxplot() +
  coord_flip()

```


## Coordinate Maps

```{r}

# Using coordinate quickmaps

nz <- map_data("nz")

ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = "white", colour = "black")

ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = "white", colour = "black") +
  coord_quickmap()

```

```{r}

# Using polar coordinates

bar <- ggplot(data = diamonds) + 
  geom_bar(
    mapping = aes(x = cut, fill = cut), 
    show.legend = FALSE,
    width = 1
  ) + 
  theme(aspect.ratio = 1) +
  labs(x = NULL, y = NULL)

bar + coord_flip()
bar + coord_polar()

```

